---

galaxy_info:
  role_name: soundness_check
  author: Dirk Haubenreisser (haubenr@de.ibm.com)
  description: Role performing various configuration soundness checks
  company: IBM
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
