---

galaxy_info:
  role_name: selinux
  author: Dirk Haubenreisser (haubenr@de.ibm.com)
  description: Role performing SELinux setup and configuration tasks
  company: IBM
  license: Apache-2.0
  min_ansible_version: "2.10"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
