---

galaxy_info:
  role_name: ocp_install_cluster
  author: Dirk Haubenreisser (haubenr@de.ibm.com)
  description: Role performing the actual RHOCP cluster installation
  company: IBM
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
