---

galaxy_info:
  role_name: crypto
  author: Dirk Haubenreisser (haubenr@de.ibm.com)
  description: Role performing setup and configuration tasks for CEX crypto hardware
  company: IBM
  license: Apache-2.0
  min_ansible_version: 2.10
  platforms:
    - name: EL
      versions: 8
