---

collections:
  - name: ansible.posix
    version: '>=1.3.0'
  - name: ansible.utils
    version: '>=2.5.0'
  - name: community.crypto
    version: '>=2.2.2'
  - name: community.general
    version: '>=4.2.0'
  - name: community.libvirt
    version: '>=1.0.2'
  - name: community.okd
    version: '>=2.1.0'
  - name: kubernetes.core
    version: '>=2.2.3'
